using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace EXO.Functions.Avatar
{
	// Token: 0x020000AF RID: 175
	internal class KeyWords
	{
		// Token: 0x06000673 RID: 1651 RVA: 0x00024DA0 File Offset: 0x00022FA0
		// Note: this type is marked as 'beforefieldinit'.
		unsafe static KeyWords()
		{
			int num = 18;
			List<string> list = new List<string>(num);
			CollectionsMarshal.SetCount<string>(list, num);
			Span<string> span = CollectionsMarshal.AsSpan<string>(list);
			int num2 = 0;
			*span[num2] = "_interact";
			num2++;
			*span[num2] = "_onDeserialization";
			num2++;
			*span[num2] = "_onDisable";
			num2++;
			*span[num2] = "_onEnable";
			num2++;
			*span[num2] = "_onOwnershipTransferred";
			num2++;
			*span[num2] = "_start";
			num2++;
			*span[num2] = "_onPlayerJoined";
			num2++;
			*span[num2] = "_onPlayerLeft";
			num2++;
			*span[num2] = "_onStationEntered";
			num2++;
			*span[num2] = "_onStationExited";
			num2++;
			*span[num2] = "_onTriggerStay";
			num2++;
			*span[num2] = "_onPlayerTriggerEnter";
			num2++;
			*span[num2] = "_onPlayerTriggerExit";
			num2++;
			*span[num2] = "_onPickup";
			num2++;
			*span[num2] = "_lateUpdate";
			num2++;
			*span[num2] = "_update";
			num2++;
			*span[num2] = "_Update";
			num2++;
			*span[num2] = "_fixedUpdate";
			num2++;
			KeyWords.DefaultUdonEvents = list;
			num2 = 16;
			List<string> list2 = new List<string>(num2);
			CollectionsMarshal.SetCount<string>(list2, num2);
			span = CollectionsMarshal.AsSpan<string>(list2);
			num = 0;
			*span[num] = "furry";
			num++;
			*span[num] = "fur";
			num++;
			*span[num] = "rex";
			num++;
			*span[num] = "rexouium";
			num++;
			*span[num] = "canine";
			num++;
			*span[num] = "proto";
			num++;
			*span[num] = "protogen";
			num++;
			*span[num] = "toaster";
			num++;
			*span[num] = "taider";
			num++;
			*span[num] = "taidum";
			num++;
			*span[num] = "wicker";
			num++;
			*span[num] = "k9";
			num++;
			*span[num] = "knot";
			num++;
			*span[num] = "nardo";
			num++;
			*span[num] = "awtter";
			num++;
			*span[num] = "awter";
			num++;
			KeyWords.furKeyWords = list2;
			num = 25;
			List<string> list3 = new List<string>(num);
			CollectionsMarshal.SetCount<string>(list3, num);
			span = CollectionsMarshal.AsSpan<string>(list3);
			num2 = 0;
			*span[num2] = "penis";
			num2++;
			*span[num2] = "benis";
			num2++;
			*span[num2] = "canine";
			num2++;
			*span[num2] = "pussy";
			num2++;
			*span[num2] = "dick";
			num2++;
			*span[num2] = "kinky";
			num2++;
			*span[num2] = "knotty";
			num2++;
			*span[num2] = "dynamic_penetration";
			num2++;
			*span[num2] = "dynamicpenetration";
			num2++;
			*span[num2] = "cock";
			num2++;
			*span[num2] = "futa";
			num2++;
			*span[num2] = "dildo";
			num2++;
			*span[num2] = "shlong";
			num2++;
			*span[num2] = "dong";
			num2++;
			*span[num2] = "vibrat";
			num2++;
			*span[num2] = "thesus";
			num2++;
			*span[num2] = "lovense";
			num2++;
			*span[num2] = "sex";
			num2++;
			*span[num2] = "hand job";
			num2++;
			*span[num2] = "plug";
			num2++;
			*span[num2] = "cum";
			num2++;
			*span[num2] = "sperm";
			num2++;
			*span[num2] = "nude";
			num2++;
			*span[num2] = "nsfw";
			num2++;
			*span[num2] = "naked";
			num2++;
			KeyWords.nsfwKeys = list3;
			num2 = 101;
			List<string> list4 = new List<string>(num2);
			CollectionsMarshal.SetCount<string>(list4, num2);
			span = CollectionsMarshal.AsSpan<string>(list4);
			num = 0;
			*span[num] = "crash";
			num++;
			*span[num] = "bluescreen";
			num++;
			*span[num] = "pckill";
			num++;
			*span[num] = "killpc";
			num++;
			*span[num] = "bpu";
			num++;
			*span[num] = "izzy";
			num++;
			*span[num] = "iterations";
			num++;
			*span[num] = "tess";
			num++;
			*span[num] = "owch";
			num++;
			*span[num] = "killradius";
			num++;
			*span[num] = "medusa";
			num++;
			*span[num] = "donttouch";
			num++;
			*span[num] = "c4";
			num++;
			*span[num] = "gang";
			num++;
			*span[num] = "boom";
			num++;
			*span[num] = "yeet";
			num++;
			*span[num] = "torus";
			num++;
			*span[num] = "dielol";
			num++;
			*span[num] = "cull-behind";
			num++;
			*span[num] = "049";
			num++;
			*span[num] = "爪卂丂ㄒ乇尺";
			num++;
			*span[num] = "几ㄖ尺卂";
			num++;
			*span[num] = "丂卂几ᗪ乇尺丂";
			num++;
			*span[num] = "\ud83d\udc2f";
			num++;
			*span[num] = "ouch";
			num++;
			*span[num] = "reeee";
			num++;
			*span[num] = "paralyzer";
			num++;
			*span[num] = "fuck";
			num++;
			*span[num] = "cunt";
			num++;
			*span[num] = "nigger";
			num++;
			*span[num] = "...";
			num++;
			*span[num] = "nigga";
			num++;
			*span[num] = "cloudie";
			num++;
			*span[num] = "cloudielovesyou";
			num++;
			*span[num] = "society";
			num++;
			*span[num] = "zyklon";
			num++;
			*span[num] = "brr";
			num++;
			*span[num] = "smack";
			num++;
			*span[num] = "smac";
			num++;
			*span[num] = "rape";
			num++;
			*span[num] = "killer";
			num++;
			*span[num] = "clap";
			num++;
			*span[num] = "entity";
			num++;
			*span[num] = "toxicity";
			num++;
			*span[num] = "toxic";
			num++;
			*span[num] = "criticalerror";
			num++;
			*span[num] = "dedsec";
			num++;
			*span[num] = "watchdogs";
			num++;
			*span[num] = "stasis";
			num++;
			*span[num] = "impimlegion";
			num++;
			*span[num] = "cicero";
			num++;
			*span[num] = "hostile";
			num++;
			*span[num] = "hack";
			num++;
			*span[num] = "citizenhack";
			num++;
			*span[num] = "p.r.o.j.e.c.t";
			num++;
			*span[num] = "forsaken";
			num++;
			*span[num] = "murda";
			num++;
			*span[num] = "hellraisers";
			num++;
			*span[num] = "gooutside";
			num++;
			*span[num] = "a.b.y.s.s";
			num++;
			*span[num] = "abyss";
			num++;
			*span[num] = "nenekosquad";
			num++;
			*span[num] = "teamtoxi";
			num++;
			*span[num] = "vibez";
			num++;
			*span[num] = "linerfamily";
			num++;
			*span[num] = "aukutonakama";
			num++;
			*span[num] = "theboys";
			num++;
			*span[num] = "blackout";
			num++;
			*span[num] = "undertaker";
			num++;
			*span[num] = "vanity";
			num++;
			*span[num] = "stickmansociety";
			num++;
			*span[num] = "hashira";
			num++;
			*span[num] = "liquidcourage";
			num++;
			*span[num] = "notsiparty";
			num++;
			*span[num] = "natzi";
			num++;
			*span[num] = "legogang";
			num++;
			*span[num] = "laughingcoffin";
			num++;
			*span[num] = "autismo";
			num++;
			*span[num] = "418";
			num++;
			*span[num] = "1-800";
			num++;
			*span[num] = "1-810";
			num++;
			*span[num] = "1800";
			num++;
			*span[num] = "1810";
			num++;
			*span[num] = "1400";
			num++;
			*span[num] = "entropy";
			num++;
			*span[num] = "anti-resurrection";
			num++;
			*span[num] = "antiressurection";
			num++;
			*span[num] = "euphoria";
			num++;
			*span[num] = "fatality";
			num++;
			*span[num] = "eternalhanahaki";
			num++;
			*span[num] = "toybox";
			num++;
			*span[num] = "evolution";
			num++;
			*span[num] = "sinister";
			num++;
			*span[num] = "exiled";
			num++;
			*span[num] = "atombomb";
			num++;
			*span[num] = "overwatch";
			num++;
			*span[num] = "westside";
			num++;
			*span[num] = "eradication";
			num++;
			*span[num] = "foreverclub";
			num++;
			*span[num] = "ministry";
			num++;
			*span[num] = "deathflower";
			num++;
			KeyWords.unsafeKeys = list4;
			num = 79;
			List<string> list5 = new List<string>(num);
			CollectionsMarshal.SetCount<string>(list5, num);
			span = CollectionsMarshal.AsSpan<string>(list5);
			num2 = 0;
			*span[num2] = "crash";
			num2++;
			*span[num2] = "bluescreen";
			num2++;
			*span[num2] = "pckill";
			num2++;
			*span[num2] = "killpc";
			num2++;
			*span[num2] = "bpu";
			num2++;
			*span[num2] = "iterations";
			num2++;
			*span[num2] = "killradius";
			num2++;
			*span[num2] = "tessellation";
			num2++;
			*span[num2] = "tesselation";
			num2++;
			*span[num2] = "medusa";
			num2++;
			*span[num2] = "torus";
			num2++;
			*span[num2] = "dielol";
			num2++;
			*span[num2] = "cull-behind";
			num2++;
			*span[num2] = "torus.049";
			num2++;
			*span[num2] = "bigasstorus";
			num2++;
			*span[num2] = "bigouch";
			num2++;
			*span[num2] = "ouchbig";
			num2++;
			*span[num2] = "爪卂丂ㄒ乇尺";
			num2++;
			*span[num2] = "几ㄖ尺卂";
			num2++;
			*span[num2] = "丂卂几ᗪ乇尺丂";
			num2++;
			*span[num2] = "\ud83d\udc2f";
			num2++;
			*span[num2] = "paralyzer";
			num2++;
			*span[num2] = "nigger";
			num2++;
			*span[num2] = "nigga";
			num2++;
			*span[num2] = "cloudie";
			num2++;
			*span[num2] = "cloudielovesyou";
			num2++;
			*span[num2] = "zyklon";
			num2++;
			*span[num2] = "killer";
			num2++;
			*span[num2] = "entity";
			num2++;
			*span[num2] = "toxicity";
			num2++;
			*span[num2] = "toxic";
			num2++;
			*span[num2] = "criticalerror";
			num2++;
			*span[num2] = "dedsec";
			num2++;
			*span[num2] = "stasis";
			num2++;
			*span[num2] = "impimlegion";
			num2++;
			*span[num2] = "cicero";
			num2++;
			*span[num2] = "hostile";
			num2++;
			*span[num2] = "citizenhack";
			num2++;
			*span[num2] = "p.r.o.j.e.c.t";
			num2++;
			*span[num2] = "forsaken";
			num2++;
			*span[num2] = "murda";
			num2++;
			*span[num2] = "hellraisers";
			num2++;
			*span[num2] = "gooutside";
			num2++;
			*span[num2] = "a.b.y.s.s";
			num2++;
			*span[num2] = "abyss";
			num2++;
			*span[num2] = "nenekosquad";
			num2++;
			*span[num2] = "teamtoxi";
			num2++;
			*span[num2] = "vibez";
			num2++;
			*span[num2] = "linerfamily";
			num2++;
			*span[num2] = "aukutonakama";
			num2++;
			*span[num2] = "theboys";
			num2++;
			*span[num2] = "blackout";
			num2++;
			*span[num2] = "undertaker";
			num2++;
			*span[num2] = "vanity";
			num2++;
			*span[num2] = "stickmansociety";
			num2++;
			*span[num2] = "hashira";
			num2++;
			*span[num2] = "liquidcourage";
			num2++;
			*span[num2] = "notsiparty";
			num2++;
			*span[num2] = "natzi";
			num2++;
			*span[num2] = "legogang";
			num2++;
			*span[num2] = "laughingcoffin";
			num2++;
			*span[num2] = "autismo";
			num2++;
			*span[num2] = "entropy";
			num2++;
			*span[num2] = "anti-resurrection";
			num2++;
			*span[num2] = "antiressurection";
			num2++;
			*span[num2] = "euphoria";
			num2++;
			*span[num2] = "fatality";
			num2++;
			*span[num2] = "eternalhanahaki";
			num2++;
			*span[num2] = "toybox";
			num2++;
			*span[num2] = "sinister";
			num2++;
			*span[num2] = "exiled";
			num2++;
			*span[num2] = "spectrum";
			num2++;
			*span[num2] = "atombomb";
			num2++;
			*span[num2] = "overwatch";
			num2++;
			*span[num2] = "westside";
			num2++;
			*span[num2] = "eradication";
			num2++;
			*span[num2] = "foreverclub";
			num2++;
			*span[num2] = "ministry";
			num2++;
			*span[num2] = "deathflower";
			num2++;
			KeyWords.veryUnsafeKeys = list5;
			num2 = 5;
			List<string> list6 = new List<string>(num2);
			CollectionsMarshal.SetCount<string>(list6, num2);
			span = CollectionsMarshal.AsSpan<string>(list6);
			num = 0;
			*span[num] = "i'm trans";
			num++;
			*span[num] = "im trans";
			num++;
			*span[num] = "i an trans";
			num++;
			*span[num] = "i am trans";
			num++;
			*span[num] = "gender\u02f8 trans";
			num++;
			KeyWords.Trans = list6;
			num = 10;
			List<string> list7 = new List<string>(num);
			CollectionsMarshal.SetCount<string>(list7, num);
			span = CollectionsMarshal.AsSpan<string>(list7);
			num2 = 0;
			*span[num2] = "he⁄him";
			num2++;
			*span[num2] = "he⁄them";
			num2++;
			*span[num2] = "he⁄they";
			num2++;
			*span[num2] = "them⁄him";
			num2++;
			*span[num2] = "they⁄him";
			num2++;
			*span[num2] = "i'm male";
			num2++;
			*span[num2] = "im male";
			num2++;
			*span[num2] = "i am male";
			num2++;
			*span[num2] = "i am a dude";
			num2++;
			*span[num2] = "gender\u02f8 male";
			num2++;
			KeyWords.Male = list7;
			num2 = 9;
			List<string> list8 = new List<string>(num2);
			CollectionsMarshal.SetCount<string>(list8, num2);
			span = CollectionsMarshal.AsSpan<string>(list8);
			num = 0;
			*span[num] = "she⁄her";
			num++;
			*span[num] = "she⁄they";
			num++;
			*span[num] = "she⁄them";
			num++;
			*span[num] = "them⁄her";
			num++;
			*span[num] = "they⁄her";
			num++;
			*span[num] = "i'm female";
			num++;
			*span[num] = "im female";
			num++;
			*span[num] = "i am female";
			num++;
			*span[num] = "gender\u02f8 female";
			num++;
			KeyWords.Female = list8;
			num = 6;
			List<string> list9 = new List<string>(num);
			CollectionsMarshal.SetCount<string>(list9, num);
			span = CollectionsMarshal.AsSpan<string>(list9);
			num2 = 0;
			*span[num2] = "they⁄them";
			num2++;
			*span[num2] = "she⁄he";
			num2++;
			*span[num2] = "she⁄him";
			num2++;
			*span[num2] = "he⁄she";
			num2++;
			*span[num2] = "he⁄her";
			num2++;
			*span[num2] = "any pronouns";
			num2++;
			KeyWords.Diverse = list9;
		}

		// Token: 0x0400030E RID: 782
		internal static readonly List<string> DefaultUdonEvents;

		// Token: 0x0400030F RID: 783
		internal static List<string> furKeyWords;

		// Token: 0x04000310 RID: 784
		internal static List<string> nsfwKeys;

		// Token: 0x04000311 RID: 785
		internal static List<string> unsafeKeys;

		// Token: 0x04000312 RID: 786
		internal static List<string> veryUnsafeKeys;

		// Token: 0x04000313 RID: 787
		internal static List<string> Trans;

		// Token: 0x04000314 RID: 788
		internal static List<string> Male;

		// Token: 0x04000315 RID: 789
		internal static List<string> Female;

		// Token: 0x04000316 RID: 790
		internal static List<string> Diverse;
	}
}
